### ISSUE TITLE
Creación y ajuste de EndPoints (MID)

### ISSUE THREAD

**Issue by a52290451** [udistrital/alternancia_mid#2]
Se debe realizar la creación y ajuste de EndPoints en alternancia_mid y las tareas que esto requiera (Creación o ajuste de controladores, helpers, modelos, rutas), para la validación y control de ingresos en la sedes y salones de la universidad.

**Comment by FelipeVel** [comment]
Tareas por hacer para completar el MID:

[x] Creación de controladores y helpers.
[x] Ajuste de enrutamiento a controladores.
[ ] Completar la lógica de negocio en los helpers.
    * [x] Consulta de API terceros (Comorbilidades y vacunación).
    * [x] Consulta de API sintomas.
    * [ ] Consulta de API Oikos (Aforo).
[x] Refactor de la respuesta del MID
[x] Conexión del cliente con el MID

**Comment by a52290451** [comment]
Una vez terminado el desarrollo en API MID, realizar commit en rama **develop**.

**Comment by FelipeVel** [comment]
Se realiza el [commit](https://github.com/udistrital/alternancia_mid/commit/30b19ee498e844fe98c7189817f36f9160a2e0e7)
