### ISSUE TITLE
Ajuste del modelo de la BD (Creación de Scripts)

### ISSUE THREAD

**Issue by a52290451** [udistrital/alternancia_mid#3]
Se debe realzar el ajuste de las tablas necesarias para relacionar salones con edificios y edificios con sedes de la universidad, según sea el caso.

**Criterio de aceptación**

- [x] Script SQL con cambios a realizar en la BD.

**Comment by FelipeVel** [comment]
El [https://drive.google.com/file/d/1ub28MEazHSra2t7hEBkj10J8egC4DN0d/view?usp=sharing](sql desarrollado) contiene partes de:

- Creación de un edificio faltante
- Eliminación de relación de edificios mal ligados
- Creación de relación de edificios con sedes
- Creación de campos de aforo y cupo
- Llenado de datos de aforo y cupo de sedes, edificios, aulas y laboratorios

**Comment by FelipeVel** [comment]
Al generar los datos reales para el script que se va a poner en producción con base en el aforo [por sedes](https://docs.google.com/spreadsheets/d/1ivQdFZyk6TmhFnaA8j3DOnfBbeD48V64/edit?usp=sharing&ouid=107699434263475311303&rtpof=true&sd=true) y [por salones](https://docs.google.com/spreadsheets/d/1jzrpmQK4ynNQRwU2oAXewEWphH4LNO-i/edit?usp=sharing&ouid=107699434263475311303&rtpof=true&sd=true), haasta el momento se tuvieron los siguientes problemas:

- Salones no encontrados:
     - Ingeniería:
          - LASER
          - NANOTECNOLOGÍA
          - PROTOTIPADO
          - FESTO
     - Ciencias:
          - MÚLTIPLE
          - COLORANTES
          - PRODUCTOS NATURALES VEGETALES
          - PREPARACIÓN DE REACTIVOS
          - NANOTECNOLOGÍA
          - BALANZAS

- Nombres incompletos de salones:
     -  Ciencias:
          - Instrumental y lab. instrumental (En BD hay instrumental 1,2 y 3
          - Laboratorio de física (En BD hay más de 5 laboratorios de física.
