### ISSUE TITLE
Ajustes en API alternancia_mid

### ISSUE THREAD

**Issue by a52290451** [udistrital/alternancia_mid#35]
Realizar ajustes necesarios en API [alternancia_mid](https://github.com/udistrital/alternancia_mid), en cuanto a:

- Hacer función post hacia nuevo API (con condiciones de no tener un mismo estudiante en dos espacios al mismo tiempo).
- Editar consultas de cupo para hacer uso del nuevo API para esta funcionalidad.

Criterios de aceptación:

- [ ] Commit en rama feature con los cambios realizados.

**Comment by JocoolQ** [comment]
Se agregan comentarios sobre posibles validaciones a considerar:

- Validar que cada estudiante sólo pueda leer el qr de ingreso o salida sólo una vez por franja horaria en espacio físico.

- En el caso de que un estudiante registre la entrada a un espacio físico pero no registre salida:
	- Si el estudiante necesita ingresar a otro espacio físico:  (Posible solución) Cuando registra el ingreso, automaticamente se registra la salida en el espacio anterior.
	- Si el estudiante necesita salir de la sede: (Posible solución) Cuando registra la salida de la sede, se registra la salida del salón.
	- NOTA: (Solución adicional) El docente registra salida del salón y se verifica que sus estudiantes registran salida, sino se les registra automaticamente la salida.

- Validar que al registrar un ingreso en un salón se haya registrado un ingreso previo válido en la sede respectiva.

**Comment by FelipeVel** [comment]
Se hacen los ajustes en el mid para que funcione con la traza del estudiante, los ajustes detallados son:

* El cupo ya no se maneja como valor en la base de datos de Oikos, ahora se hace un conteo de los registros dentro del espacio y se calcula el cupo en tiempo real.
* Se integra con el crud de seguimiento para que allí se pueda llevar un registro de la traza de cada persona.
* Se añaden endpoints que completan la información guardada en seguimiento, esto con el fin de que la información sea más entendible y organizada.
